### ISSUE TITLE
Support MySQL 5.X as a target

### ISSUE THREAD

**Issue by bobvawter** [cockroachdb/replicator#988]
These older versions of MySQL don't support CTE's, which, at a minimum, prevents the schema-inspection queries from running. There may be other unknown-unknown's in terms of SQL workload changes.

**Comment by ryanluu12345** [comment]
My understanding here is that we need to just add a new set of queries that don't use CTEs for MySQL and then drill in the version of the database throughout the codebase so that we can know when to use the MySQL 5.7 queries

**Comment by bobvawter** [comment]
Adding support in `schemawatch` is the first identified task.

Run `TEST_TARGET_CONNECT=mysql://root:SoupOrSecret@localhost:3306/ go test ./...` to validate.

**Comment by bobvawter** [comment]
Possibly an opportunity for #996

**Comment by ryanluu12345** [comment]
Yep, I see what you mean by adding support in `schemwatch`. I see the query templates inside of `internal/target/schemawatch/dependencies.go`. Based on my read, it looks like we'll just need to add a new `mysql5_7` template and then update the MySQL case statement so that if we see version 5.7, we use the new query without CTEs.

**Comment by ryanluu12345** [comment]
Regarding #996, I can take a look at that once I get this base functionality working. Then can refactor this so it applies to all templates for every dialect.
