### ISSUE TITLE
MarkApplied can send over-large payloads

### ISSUE THREAD

**Issue by bobvawter** [cockroachdb/replicator#995]
It's possible to exceed `sql.conn.max_read_buffer_message_size` if a bulk operation has been processed which contained millions of rows. The `MarkApplied()` method should segment its work, opening a transaction if one was not already provided. It would be tempting to mark all mutations applied at some timestamp, but this could mask situations in which a row was written to staging out-of-sequence and would not be detected by the consistency check query.

**Comment by ryanluu12345** [comment]
Hi @bobvawter , I understand the gist that we can exceed the limit here and because of that we need to segment work so that each segment can be under the limit.

Is the ask here mainly to break up the work into a set of transactions? Or the same transactions but just different INSERT queries within that transaction?

Also, are there ways to set this max buffer size low so that we can trigger this behavior for testing without doing millions of rows?

**Comment by bobvawter** [comment]
Same transaction. 

https://pkg.go.dev/github.com/cockroachdb/replicator@v1.0.3/internal/util/batches#Window
